version: "3.3"
services:
  eureka-server:
    image: "config-server:latest"
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: config-server
    volumes:
    - /opt/config-server:/opt/device/config-server
    network_mode: host
    ports:
      - "30888:30888"
    extra_hosts:
      - "host:192.168.3.31"
    healthcheck:
      test: curl --fail -s http://localhost:30888/health || exit 1
      interval: 30s
      timeout: 2m
      retries: 3
#    networks:
#      - host
