server:
  port: 5555

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: device-service
          uri: lb://device-service
#          uri: http://192.168.3.31:9003
          predicates:
            - Path=/api/device/**
          filters:
            - RewritePath=/api/device/(?<segment>.*), /$\{segment}
        - id: device-service-doc
          uri: lb://device-service
          predicates:
            - Path=/doc/device-service/**
          filters:
            - RewritePath=/doc/device-service/(?<segment>.*), /$\{segment}

eureka:
  instance:
    ip-address: true
  client:
    service-url:
      defaultZone:
        http://192.168.3.31:30761/eureka/






