server:
  port: 5555

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: device-service
          uri: lb://device-service
          predicates:
            - Path=/device/**


eureka:
  instance:
    ip-address: true
  client:
    service-url:
      defaultZone:
        http://192.168.3.31:30761/eureka/






